# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
#
# .travis.yml file examples:
#
#  * https://github.com/cdeterman/gpuR/blob/develop/.travis.yml

# whitelist branches
branches:
  only:
    - master

language: r
sudo: false
warnings_are_errors: false
cache: packages

r:
  - oldrel
  - release
  - devel

addons:
  apt:
    packages:
#      - libcurl4-openssl-dev
#      - libgdal-dev
#      - libgeos-dev
#      - libjq-dev
#      - libproj-dev
#      - libprotobuf-dev
#      - libssl-dev
#      - libudunits2-dev
#      - libv8-dev
#      - protobuf-compiler

# R packages
r_packages:
 - rmarkdown
 - webshot

# Latest updates from GitHub
#r_github_packages:
#  - mazamascience/MazamaCoreUtils

#after_success:
#  - R CMD INSTALL $PKG_TARBALL
#  - Rscript -e 'lintr::lint_package()'

